### ISSUE TITLE
Can't find flame.ply under 018.zip 

### ISSUE THREAD

**Issue by Sulwon-0516** [tobias-kirschstein/diffusion-avatars#1]
Hello,

Thank you for sharing the code of your impressive research!

Here I open an issue as I meet an error while running tests with the provided code.

When I run the following code,

```bash
python scripts/render/render_trajectory.py DA-1

```

I encounter an error saying that there's no `flame.ply` file in the directory. When I check the original zip file, it seems like `flame.ply` is missing. Is this intended?

```
ValueError: string is not a file: /media/ssd1/inhee/dataset/diffusion-avatars/demo_dataset_unzipped/data_path/nersemble/018/flame.ply
```

Thank you!

**Comment by richardchenbuaa** [comment]
same problem encountered. Please do not use 018 case for testing because of missing flame.ply file.

**Comment by tobias-kirschstein** [comment]
Thank you for reporting this. I finally managed to add the `flame.ply` for subject `018`.
Can you please try again?
